[2024-09-23T18:04:43.446+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:04:41.767643+00:00 [queued]>
[2024-09-23T18:04:43.474+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:04:41.767643+00:00 [queued]>
[2024-09-23T18:04:43.475+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:04:43.476+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:04:43.477+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:04:43.498+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-09-23 18:04:41.767643+00:00
[2024-09-23T18:04:43.507+0000] {standard_task_runner.py:55} INFO - Started process 14491 to run task
[2024-09-23T18:04:43.513+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-09-23T18:04:41.767643+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvyaartck']
[2024-09-23T18:04:43.517+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask is_api_available
[2024-09-23T18:04:43.630+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:04:41.767643+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:04:43.744+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:04:41.767643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:04:41.767643+00:00
[2024-09-23T18:04:43.747+0000] {http.py:120} INFO - Poking: api/
[2024-09-23T18:04:43.768+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-09-23T18:04:43.774+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-09-23T18:04:44.163+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-09-23T18:04:44.180+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240923T180441, start_date=20240923T180443, end_date=20240923T180444
[2024-09-23T18:04:44.211+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:04:44.238+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
