[2024-09-23T18:02:40.727+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:02:37.435668+00:00 [queued]>
[2024-09-23T18:02:40.747+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:02:37.435668+00:00 [queued]>
[2024-09-23T18:02:40.749+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:02:40.750+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:02:40.751+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:02:40.778+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-23 18:02:37.435668+00:00
[2024-09-23T18:02:40.790+0000] {standard_task_runner.py:55} INFO - Started process 14385 to run task
[2024-09-23T18:02:40.799+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2024-09-23T18:02:37.435668+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp4rjr5r1a']
[2024-09-23T18:02:40.804+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask create_table
[2024-09-23T18:02:40.966+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2024-09-23T18:02:37.435668+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:02:41.159+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:02:37.435668+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:02:37.435668+00:00
[2024-09-23T18:02:41.189+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-09-23T18:02:41.202+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-09-23T18:02:41.206+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-09-23T18:02:41.228+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240923T180237, start_date=20240923T180240, end_date=20240923T180241
[2024-09-23T18:02:41.296+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:02:41.341+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
